# Generated by Django 5.0.6 on 2024-05-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='google_location',
        ),
        migrations.RemoveField(
            model_name='property',
            name='name',
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='micro_market',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='parcel_size',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='prize_per_acre',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=True, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=True, max_digits=9),
            preserve_default=False,
        ),
    ]
