# Generated by Django 5.0.6 on 2024-05-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0002_remove_property_google_location_remove_property_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
