# Generated by Django 5.0.6 on 2024-05-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0003_property_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('parcel_size', models.CharField(max_length=255)),
                ('price_per_acre', models.CharField(max_length=255)),
                ('micro_market', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
