# Generated by Django 5.0.6 on 2024-06-05 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0004_location_delete_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='property_id',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('percentage_of_commission', models.IntegerField(default=0)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.location')),
            ],
        ),
    ]
