# Generated by Django 5.0.6 on 2024-06-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0005_location_property_id_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
