# Generated by Django 5.0.6 on 2024-06-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0006_location_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='total_visits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
