# Generated by Django 5.0.6 on 2024-06-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0007_location_total_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='parcel_size',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='price_per_acre',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
