# Generated by Django 5.0.6 on 2024-06-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0008_alter_location_parcel_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='date',
            field=models.DateField(default='2022-12-12'),
            preserve_default=False,
        ),
    ]
