# Generated by Django 5.0.6 on 2024-06-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0009_location_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='total_visits',
            field=models.IntegerField(default=0),
        ),
    ]
